# Generated by Django 5.2.3 on 2025-06-23 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
